[package]
name = "basic-linux-in-rust"
version = "0.1.0"
authors = ["shinooooo <bjys1290150@gn.iwasaki.ac.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
